import {
  sourceArtifactsSchema,
  validateSourceArtifacts,
  staticSourceTypes,
} from "./source-artifacts.js";
import { validateSourceLinks } from "./source-formats.js";
import { z } from "zod";
import { hash, requireThat } from "./core.js";
import { answerTemplatesSchema } from "./answer-style.js";

// A published knowledge package is pages + golden QA cases + pinned config.
// The structured procedure model (inputs/branches/nodes/guidance) was removed
// by ADR-0004; answers are retrieved from pages and generated by the model.
export const identifier = z.string().regex(/^[a-zA-Z0-9_-]{1,100}$/);
export const bundleSchema = z
  .object({
    pages: z
      .array(
        z
          .object({
            id: identifier,
            path: z.string().min(1).max(300),
            title: z.string().min(1).max(300),
            content: z.string().max(200000),
            hash: z.string().length(64),
          })
          .strict(),
      )
      .min(1)
      .max(500),
    sourceArtifacts: sourceArtifactsSchema.optional(),
    cases: z
      .array(
        z
          .object({
            id: identifier,
            question: z.string().min(1).max(4000),
            style: z.enum(["business", "technical"]).optional(),
            depth: z.enum(["beginner", "experienced"]).optional(),
            expectedOutcome: z
              .enum(["answer", "knowledge_gap", "clarification"])
              .optional(),
            expectedCitations: z.array(identifier).max(20).optional(),
          })
          .strict(),
      )
      .min(1)
      .max(100),
    config: z
      .object({
        domainLabel: z.string().min(1).max(100).optional(),
        answerTemplates: answerTemplatesSchema.optional(),
        model: z.string().min(1).max(200),
        modelRevision: z.string().min(1).max(200),
        promptVersion: z.literal("1"),
        templateVersion: z.literal("1"),
        retrievalVersion: z.literal("1"),
        protocolVersion: z.literal("1"),
        evaluationVersion: z.string().min(1).max(100),
      })
      .strict(),
  })
  .strict();
export type Bundle = z.infer<typeof bundleSchema>;
export type Page = Bundle["pages"][number];

function unique(values: string[]) {
  return new Set(values).size === values.length;
}

export function validateBundle(bundle: Bundle): void {
  requireThat(unique(bundle.cases.map((c) => c.id)), 400, "DUPLICATE_CASE");
  requireThat(
    unique(bundle.pages.map((p) => p.id)) &&
      unique(bundle.pages.map((p) => p.path)),
    400,
    "DUPLICATE_ID",
  );
  for (const page of bundle.pages) {
    requireThat(
      !page.path.startsWith("/") &&
        !page.path.includes("\\") &&
        page.path
          .split("/")
          .every(
            (s) =>
              /^[\p{L}\p{N}_ .-]+$/u.test(s) &&
              !s.startsWith(".") &&
              s.trim() === s,
          ) &&
        page.path.endsWith(".md"),
      400,
      "INVALID_PAGE_PATH",
    );
    requireThat(hash(page.content) === page.hash, 400, "CONTENT_HASH_MISMATCH");
  }
  if (bundle.sourceArtifacts) {
    const artifacts = validateSourceArtifacts(
      bundle.sourceArtifacts,
      staticSourceTypes,
    );
    requireThat(
      !artifacts.some((a) =>
        bundle.pages.some((p) => p.id === a.id || p.path === a.path),
      ),
      400,
      "DUPLICATE_SOURCE_ARTIFACT",
    );
  }
  validateSourceLinks(
    bundle.pages,
    (bundle.sourceArtifacts ?? []).map((a) => a.path),
  );
  for (const c of bundle.cases)
    requireThat(
      (c.expectedCitations ?? []).every((id) =>
        bundle.pages.some((page) => page.id === id),
      ),
      400,
      "INVALID_CITATION",
    );
}
